//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TeknikServis_ve_Urun_Takip_Sistemi_Web_Kismi
{
    public partial class WebForm1
    {
    }
}
